AWSTemplateFormatVersion: 2010-09-09
Description: WebPageTest.org
Parameters:
  Region:
    Type: String
    Default: eu-west-1
  Initials:
    Type: String
  Prefix:
    Type: String
  ContactEmail:
    Type: String
  IngressVpcCIDR:
    Type: String
  DomainName:
    Type: String
  HostedZoneId:
    Type: String
  NetworkVpc:
    Type: AWS::EC2::VPC::Id
  WPTClientSubnet:
    Type: AWS::EC2::Subnet::Id
  WPTALBSubnets:
      Description: Choose which subnets the Application Load Balancer should be deployed to
      Type: List<AWS::EC2::Subnet::Id>
  WPTServerInstanceType:
    Type: String
    Default: t2.medium
    AllowedValues:
      - t2.micro
      - t2.small
      - t2.medium
      - t2.large
  WPTClientInstanceType:
    Type: String
    Default: c4.large
  WPTServerAMI:
    Type: String
    Default: ami-9978f6ee
  KeypairName:
    Description: Name of an existing EC2 KeyPair to enable SSH access to the instance
    Type: AWS::EC2::KeyPair::KeyName
    ConstraintDescription: must be the name of an existing EC2 KeyPair.
  AWSAccessKey:
    Type: String
    NoEcho: true
  AWSSecretKey:
    Type: String
    NoEcho: true
Resources:
  WPTServerSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: SG for WPT server
      VpcId: !Ref NetworkVpc
      SecurityGroupIngress:
        - IpProtocol: -1
          FromPort: -1
          ToPort: -1
          CidrIp: !Ref IngressVpcCIDR
        - IpProtocol: -1
          FromPort: -1
          ToPort: -1
          SourceSecurityGroupId: !Ref WPTClientSecurityGroup
        - IpProtocol: -1
          FromPort: -1
          ToPort: -1
          SourceSecurityGroupId: !Ref ALBSecurityGroup
      Tags:
        - Key: Name
          Value: !Sub '${Prefix}-${Initials}-wpt-server-sg'
  WPTClientSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: SG for WPT Client
      VpcId: !Ref NetworkVpc
      Tags:
        - Key: Name
          Value: !Sub '${Prefix}-${Initials}-wpt-client-sg'
  ALBSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: SG for ALB
      VpcId: !Ref NetworkVpc
      SecurityGroupIngress:
        - IpProtocol: -1
          FromPort: -1
          ToPort: -1
          CidrIp: !Ref IngressVpcCIDR
        - IpProtocol: -1
          FromPort: -1
          ToPort: -1
          SourceSecurityGroupId: !Ref WPTClientSecurityGroup
      Tags:
        - Key: Name
          Value: !Sub '${Prefix}-${Initials}-wpt-alb-sg'
  WPTArchiveBucket:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: Private
      LifecycleConfiguration:
        Rules:
          - Id: GlacierRule
            Prefix: glacier
            Status: Enabled
            ExpirationInDays: 120
            Transitions:
              - TransitionInDays: 60
                StorageClass: Glacier
      Tags:
        - Key: Name
          Value: !Sub '${Prefix}-${Initials}-wpt-bucket'
  WPTRecordSetGroup:
    Type: AWS::Route53::RecordSetGroup
    Properties:
      HostedZoneId: !Ref HostedZoneId
      Comment: RecordSet group for WebPageTest
      RecordSets:
        - Name: !Sub 'wpt-${Initials}.${DomainName}.'
          Type: A
          AliasTarget:
            HostedZoneId: !GetAtt ALBWPT.CanonicalHostedZoneID
            DNSName: !GetAtt ALBWPT.DNSName
  ALBWPT:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Scheme: internet-facing
      Subnets: !Ref WPTALBSubnets
      LoadBalancerAttributes:
        - Key: idle_timeout.timeout_seconds
          Value: 50
      SecurityGroups: [!Ref ALBSecurityGroup]
  ALBWPTListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn: !Ref ALBWPT
      Port: 80
      Protocol: HTTP
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref WPTTargetGroup
  WPTTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      HealthCheckPath: /
      HealthCheckIntervalSeconds: 30
      HealthCheckProtocol: HTTP
      HealthCheckTimeoutSeconds: 10
      HealthyThresholdCount: 4
      Matcher:
        HttpCode: '200'
      Port: 80
      Protocol: HTTP
      TargetGroupAttributes:
        - Key: deregistration_delay.timeout_seconds
          Value: '20'
      UnhealthyThresholdCount: 3
      VpcId: !Ref NetworkVpc
  WPTAutoScalingGroup:
    Type: "AWS::AutoScaling::AutoScalingGroup"
    # CreationPolicy:
    #   AutoScalingCreationPolicy:
    #     MinSuccessfulInstancesPercent: 100
    #   ResourceSignal:
    #     Timeout: PT10M
    UpdatePolicy:
      AutoScalingRollingUpdate:
        MinInstancesInService: 0
        MaxBatchSize: 1
        SuspendProcesses:
          - HealthCheck
          - ReplaceUnhealthy
          - AZRebalance
          - AlarmNotification
          - ScheduledActions
      # AutoScalingReplacingUpdate:
      #   WillReplace: true
    Properties:
      VPCZoneIdentifier: !Ref WPTALBSubnets
      LaunchConfigurationName: !Ref WPTLaunchConfig
      HealthCheckType: ELB
      HealthCheckGracePeriod: 300
      MinSize: 1
      DesiredCapacity: 1
      MaxSize: 1
      TargetGroupARNs: [!Ref WPTTargetGroup]
      Tags:
        - Key: Name
          Value: !Sub '${Prefix}-${Initials}-wpt-server'
          PropagateAtLaunch: true
  WPTLaunchConfig:
    Type: AWS::AutoScaling::LaunchConfiguration
    Properties:
      ImageId: !Ref WPTServerAMI
      KeyName: !Ref KeypairName
      SecurityGroups: [!Ref WPTServerSecurityGroup]
      InstanceType: !Ref WPTServerInstanceType
      UserData:
        Fn::Base64: !Sub |
          ec2_key=${AWSAccessKey}
          ec2_secret=${AWSSecretKey}
          headless=0
          iq=80
          pngss=1
          ec2_instance_size=${WPTClientInstanceType}
          EC2.default=${Region}
          EC2.${Region}.securityGroup=${WPTClientSecurityGroup}
          EC2.${Region}.subnetId=${WPTClientSubnet}
          EC2.ScaleFactor=50
          EC2.${Region}.min=1
          EC2.${Region}.max=10
          ec2_prune_volumes=1
          contact=${ContactEmail}
          publishTo=
          waterfall_show_user_timing=1
          maxruns=400
          allowNonFQDN=1
          medianMetric=SpeedIndex
          shard_tests=1
          allowPrivate=1
          UAModifier=
          ec2_use_server_private_ip=1
          archive_s3_server=s3.amazonaws.com
          archive_s3_key=${AWSAccessKey}
          archive_s3_secret=${AWSSecretKey}
          archive_s3_bucket=${WPTArchiveBucket}
          archive_days=0
          cron_archive=1
          api_key=2018
          host=wpt-${Initials}.${DomainName}
Outputs:
  DnsName:
    Value: !GetAtt ALBWPT.DNSName
  WPTArchiveBucketEndpoint:
    Value: !GetAtt WPTArchiveBucket.DomainName
  URLWPT:
    Value: wpt-${Initials}.${DomainName}
