---
AWSTemplateFormatVersion: '2010-09-09'
Description: "A simple stack to create an EC2 with network's resources correctly formed."

Parameters:
  ProjectName:
    Type: String
    Default: sandbox
  Region:
    Type: String
    Default: eu-west-1
  Initials:
    Type: String
    Default: undefined

Resources:
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsSupport: 'true'
      EnableDnsHostnames: 'true'
      Tags:
      - Key: Name
        Value: !Sub '${ProjectName}-${Region}-${Initials}'

  PublicSubnet:
    Type: "AWS::EC2::Subnet"
    Properties:
      VpcId: !Ref VPC
      CidrBlock: 10.0.0.0/24
      AvailabilityZone: !Sub '${Region}a'
      MapPublicIpOnLaunch: 'true'
      Tags:
        - Key: Name
          Value: !Sub '${ProjectName}-${Region}-${Initials}-public'
        - Key: Description
          Value: !Sub '${ProjectName}-${Region}-${Initials} public subnet in AZ ${Region}a'
