---
AWSTemplateFormatVersion: '2010-09-09'
Description: "Creates the landscape for our environment"

Resources:
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsSupport: 'true'
      EnableDnsHostnames: 'true'
      Tags:
      - Key: Name
        Value: "sandbox-eu-west-1-jd"
