---
- hosts: "{{ target|default('all') }}"
  become: yes
  gather_facts: no

  tasks:
    - name:
      shell: >-
        curl --silent --location https://rpm.nodesource.com/setup_10.x | sudo bash -

    - yum: # TODO : handle different linux families
        name: "{{ item }}"
        update_cache: yes
      with_items:
        - vim
        - curl
        - git
        - nodejs
