AWSTemplateFormatVersion: 2010-09-09
Description: CloudFront Simple Test
Parameters:
  Region:
    Type: String
    Default: eu-west-1
  Initials:
    Type: String
  DomainName:
    Type: String
Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub 'sbx-${Initials}-cftest.${DomainName}'
      AccessControl: PublicRead
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: error.html
  S3BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket:
        Ref: S3Bucket
      PolicyDocument:
        Statement:
          -
            Sid: PublicReadGetObject
            Effect: Allow
            Principal: "*"
            Action: s3:GetObject
            Resource: !Sub 'arn:aws:s3:::sbx-${Initials}-cftest.${DomainName}/*'
  DNSRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneName: !Sub '${DomainName}.'
      Name: !Sub 'sbx-${Initials}-cftest.${DomainName}.'
      Type: A
      AliasTarget:
        DNSName: "s3-website-eu-west-1.amazonaws.com"
        EvaluateTargetHealth: false
        HostedZoneId: "Z1BKCTXD74EZPE"
  CFDistrib:
    Type: "AWS::CloudFront::Distribution"
    Properties:
      DistributionConfig:
        S3Origin:
          DNSName: !Sub '${S3Bucket.DomainName}'
        Enabled: 'true'
      Tags:
        - Key: Name
          Value: !Sub 'sbx-${Initials}-cftest.${DomainName}'
Outputs:
  WebsiteURL:
    Value: !GetAtt [S3Bucket, WebsiteURL]
