AWSTemplateFormatVersion: 2010-09-09
Description: Simple VPC
Parameters:
  Env:
    Type: String
  S3TemplatePath:
    Type: String
  Region:
    Type: String
    Default: eu-west-1
  VpcCidr:
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/(1[6-9]|2[0-8]))$
    Type: String
  PublicSubnetCidrA:
    Type: String
  PublicSubnetCidrB:
    Type: String
  PublicSubnetCidrC:
    Type: String
  PrivateSubnetCidrA:
    Type: String
  PrivateSubnetCidrB:
    Type: String
  PrivateSubnetCidrC:
    Type: String
Resources:
  Vpc:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref VpcCidr
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: !Sub '${Env}-vpc'
  SubnetStackA:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub '${S3TemplatePath}/subnet-stack.yml'
      Parameters:
        Env: !Ref 'Env'
        VpcId: !Ref 'Vpc'
        PublicSubnetCidr: !Ref 'PublicSubnetCidrA'
        PrivateSubnetCidr: !Ref 'PrivateSubnetCidrA'
        AZ: !Sub '${Region}a'
      Tags:
        - Key: Stack
          Value: !Ref 'AWS::StackName'
  SubnetStackB:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub '${S3TemplatePath}/subnet-stack.yml'
      Parameters:
        Env: !Ref 'Env'
        VpcId: !Ref 'Vpc'
        PublicSubnetCidr: !Ref 'PublicSubnetCidrB'
        PrivateSubnetCidr: !Ref 'PrivateSubnetCidrB'
        AZ: !Sub '${Region}b'
      Tags:
        - Key: Stack
          Value: !Ref 'AWS::StackName'
  SubnetStackC:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub '${S3TemplatePath}/subnet-stack.yml'
      Parameters:
        Env: !Ref 'Env'
        VpcId: !Ref 'Vpc'
        PublicSubnetCidr: !Ref 'PublicSubnetCidrC'
        PrivateSubnetCidr: !Ref 'PrivateSubnetCidrC'
        AZ: !Sub '${Region}c'
      Tags:
        - Key: Stack
          Value: !Ref 'AWS::StackName'
  Igw:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: !Sub '${Env}-igw'
  IgwAttach:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      InternetGatewayId: !Ref Igw
      VpcId: !Ref Vpc
# Outputs:
